services:
  - type: web
    name: cangwei-man-shang
    env: node
    plan: free
    buildCommand: NODE_ENV=development npm install && NODE_ENV=development npm run build
    startCommand: NODE_ENV=production node server.js
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
